-- Datos de EJEMPLO generados por seed/build-seed.mjs. No editar a mano.
DELETE FROM stock_movements; DELETE FROM product_images; DELETE FROM product_variants;
DELETE FROM products; DELETE FROM categories; DELETE FROM season_events; DELETE FROM staff_users;
DELETE FROM sqlite_sequence WHERE name IN ('categories','products','product_variants','product_images','stock_movements','season_events','staff_users');
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (1, 'Alimento', 'alimento', 'Concentrado seco y húmedo para cada etapa.', 'ambos', 1);
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (2, 'Snacks', 'snacks', 'Para el antojo de media tarde.', 'ambos', 2);
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (3, 'Premios', 'premios', 'Recompensas pequeñas para entrenar y consentir.', 'ambos', 3);
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (4, 'Collares', 'collares', 'Cómodos, ajustables y con argolla para la placa.', 'ambos', 4);
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (5, 'Correas', 'correas', 'Para paseos largos por el parque.', 'perro', 5);
INSERT INTO categories (id, name, slug, description, species, sort_order) VALUES (6, 'Platos', 'platos', 'Comederos y bebederos que no se voltean.', 'ambos', 6);
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (1, 'Concentrado adulto raza mediana pollo y arroz', 'concentrado-adulto-raza-mediana-pollo-y-arroz', 'Croquetas de tamaño medio con proteína de pollo como primer ingrediente. Para perros adultos de 10 a 25 kg.', 1, 'perro', 'Campo Verde', 'Peso', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (1, 1, '2 kg', 'MAYA-001-1', '2000000000015', 38900, NULL, 14, 4, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (1, 14, 14, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (2, 1, '8 kg', 'MAYA-001-2', '2000000000022', 129900, 142000, 6, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (2, 6, 6, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (3, 1, '15 kg', 'MAYA-001-3', '2000000000039', 219900, NULL, 3, 2, 2);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (3, 3, 3, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (2, 'Concentrado cachorro raza pequeña', 'concentrado-cachorro-raza-pequena', 'Croqueta pequeña y blanda para dientes de leche, con DHA.', 1, 'perro', 'Campo Verde', 'Peso', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (4, 2, '1 kg', 'MAYA-002-1', '2000000000046', 24900, NULL, 10, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (4, 10, 10, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (5, 2, '4 kg', 'MAYA-002-2', '2000000000053', 79900, NULL, 5, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (5, 5, 5, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (3, 'Alimento gato adulto salmón', 'alimento-gato-adulto-salmon', 'Receta con salmón y control de bolas de pelo para gatos de interior.', 1, 'gato', 'Gatuno', 'Peso', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (6, 3, '1.5 kg', 'MAYA-003-1', '2000000000060', 42900, NULL, 9, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (6, 9, 9, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (7, 3, '7 kg', 'MAYA-003-2', '2000000000077', 168000, 185000, 4, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (7, 4, 4, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (4, 'Alimento gato esterilizado', 'alimento-gato-esterilizado', 'Menos grasa y más fibra para gatos esterilizados que prefieren el sofá.', 1, 'gato', 'Gatuno', 'Peso', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (8, 4, '1.5 kg', 'MAYA-004-1', '2000000000084', 45900, NULL, 2, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (8, 2, 2, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (9, 4, '7 kg', 'MAYA-004-2', '2000000000091', 174000, NULL, 0, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (9, 0, 0, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (5, 'Sobre húmedo gato pavo en salsa', 'sobre-humedo-gato-pavo-en-salsa', 'Trocitos en salsa, 85 g. Ideal para mezclar con el concentrado.', 1, 'gato', 'Gatuno', 'Presentación', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (10, 5, '1 sobre', 'MAYA-005-1', '2000000000107', 3900, NULL, 60, 12, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (10, 60, 60, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (11, 5, 'Caja x 12', 'MAYA-005-2', '2000000000114', 42000, 46800, 8, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (11, 8, 8, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (6, 'Galletas de avena y manzana', 'galletas-de-avena-y-manzana', 'Horneadas, sin colorantes. Crujientes por fuera, suaves por dentro.', 2, 'perro', 'Huellitas', 'Sabor', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (12, 6, 'Avena y manzana 200 g', 'MAYA-006-1', '2000000000121', 14900, NULL, 22, 5, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (12, 22, 22, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (13, 6, 'Mantequilla de maní 200 g', 'MAYA-006-2', '2000000000138', 15900, NULL, 18, 5, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (13, 18, 18, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (7, 'Palitos dentales', 'palitos-dentales', 'Ayudan a reducir el sarro mientras mastica. Bolsa x 7.', 2, 'perro', 'Huellitas', 'Tamaño', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (14, 7, 'Raza pequeña', 'MAYA-007-1', '2000000000145', 18900, NULL, 15, 4, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (14, 15, 15, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (15, 7, 'Raza grande', 'MAYA-007-2', '2000000000152', 24900, NULL, 7, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (15, 7, 7, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (8, 'Crema lamible para gato atún', 'crema-lamible-para-gato-atun', 'Tubitos de crema para dar en la mano. El momento favorito del día.', 2, 'gato', 'Gatuno', 'Presentación', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (16, 8, 'Pack x 4', 'MAYA-008-1', '2000000000169', 9900, NULL, 30, 8, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (16, 30, 30, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (17, 8, 'Pack x 20', 'MAYA-008-2', '2000000000176', 44900, 49500, 6, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (17, 6, 6, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (9, 'Hígado deshidratado', 'higado-deshidratado', 'Un solo ingrediente: hígado de res. Se parte con la mano en trocitos.', 3, 'ambos', 'Campo Verde', 'Peso', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (18, 9, '80 g', 'MAYA-009-1', '2000000000183', 16900, NULL, 12, 4, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (18, 12, 12, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (19, 9, '250 g', 'MAYA-009-2', '2000000000190', 42900, NULL, 4, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (19, 4, 4, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (10, 'Premios de entrenamiento pollo', 'premios-de-entrenamiento-pollo', 'Bocados pequeños y bajos en calorías para repetir muchas veces.', 3, 'perro', 'Huellitas', 'Sabor', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (20, 10, 'Pollo 150 g', 'MAYA-010-1', '2000000000206', 13900, NULL, 25, 6, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (20, 25, 25, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (21, 10, 'Cordero 150 g', 'MAYA-010-2', '2000000000213', 14900, NULL, 11, 6, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (21, 11, 11, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (11, 'Hierba gatera orgánica', 'hierba-gatera-organica', 'Catnip seco para espolvorear sobre su rascador o juguete.', 3, 'gato', 'Gatuno', 'Presentación', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (22, 11, 'Frasco 20 g', 'MAYA-011-1', '2000000000220', 12900, NULL, 9, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (22, 9, 9, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (12, 'Collar acolchado ajustable', 'collar-acolchado-ajustable', 'Interior acolchado que no irrita el cuello y hebilla de liberación rápida.', 4, 'perro', 'Maya Básicos', 'Talla', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (23, 12, 'S', 'MAYA-012-1', '2000000000237', 24900, NULL, 8, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (23, 8, 8, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (24, 12, 'M', 'MAYA-012-2', '2000000000244', 27900, NULL, 10, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (24, 10, 10, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (25, 12, 'L', 'MAYA-012-3', '2000000000251', 31900, NULL, 2, 3, 2);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (25, 2, 2, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (13, 'Collar reflectivo con placa', 'collar-reflectivo-con-placa', 'Cinta reflectiva para los paseos de la noche. Incluye placa para grabar.', 4, 'perro', 'Maya Básicos', 'Talla', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (26, 13, 'S', 'MAYA-013-1', '2000000000268', 34900, NULL, 6, 2, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (26, 6, 6, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (27, 13, 'M', 'MAYA-013-2', '2000000000275', 36900, NULL, 5, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (27, 5, 5, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (28, 13, 'L', 'MAYA-013-3', '2000000000282', 39900, NULL, 4, 2, 2);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (28, 4, 4, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (14, 'Collar para gato con cascabel', 'collar-para-gato-con-cascabel', 'Con broche de seguridad que se abre si se engancha.', 4, 'gato', 'Gatuno', 'Color', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (29, 14, 'Verde petróleo', 'MAYA-014-1', '2000000000299', 14900, NULL, 12, 4, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (29, 12, 12, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (30, 14, 'Amarillo', 'MAYA-014-2', '2000000000305', 14900, NULL, 9, 4, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (30, 9, 9, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (15, 'Correa de nylon 1.5 m', 'correa-de-nylon-1-5-m', 'Mango acolchado y mosquetón giratorio que no se enreda.', 5, 'perro', 'Maya Básicos', 'Talla', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (31, 15, 'Delgada', 'MAYA-015-1', '2000000000312', 29900, NULL, 9, 3, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (31, 9, 9, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (32, 15, 'Gruesa', 'MAYA-015-2', '2000000000329', 34900, NULL, 7, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (32, 7, 7, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (16, 'Correa retráctil 5 m', 'correa-retractil-5-m', 'Freno con un solo botón. Para perros de hasta 25 kg.', 5, 'perro', 'Campo Verde', 'Tamaño', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (33, 16, 'Hasta 12 kg', 'MAYA-016-1', '2000000000336', 59900, 69900, 4, 2, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (33, 4, 4, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (34, 16, 'Hasta 25 kg', 'MAYA-016-2', '2000000000343', 74900, NULL, 3, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (34, 3, 3, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (17, 'Arnés pechera antitirones', 'arnes-pechera-antitirones', 'Argolla delantera que corrige el tirón sin presionar el cuello.', 5, 'perro', 'Maya Básicos', 'Talla', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (35, 17, 'S', 'MAYA-017-1', '2000000000350', 54900, NULL, 5, 2, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (35, 5, 5, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (36, 17, 'M', 'MAYA-017-2', '2000000000367', 59900, NULL, 6, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (36, 6, 6, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (37, 17, 'L', 'MAYA-017-3', '2000000000374', 64900, NULL, 1, 2, 2);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (37, 1, 1, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (18, 'Plato de acero antideslizante', 'plato-de-acero-antideslizante', 'Acero inoxidable con base de caucho. Va a la lavadora de platos.', 6, 'ambos', 'Maya Básicos', 'Tamaño', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (38, 18, '500 ml', 'MAYA-018-1', '2000000000381', 19900, NULL, 16, 4, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (38, 16, 16, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (39, 18, '1.2 L', 'MAYA-018-2', '2000000000398', 27900, NULL, 9, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (39, 9, 9, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (19, 'Comedero lento laberinto', 'comedero-lento-laberinto', 'Para los que comen en diez segundos: el laberinto alarga la comida y evita el atoro.', 6, 'perro', 'Huellitas', 'Color', 1);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (40, 19, 'Verde petróleo', 'MAYA-019-1', '2000000000404', 39900, NULL, 7, 2, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (40, 7, 7, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (41, 19, 'Amarillo', 'MAYA-019-2', '2000000000411', 39900, NULL, 5, 2, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (41, 5, 5, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO products (id, name, slug, description, category_id, species, brand, variant_label, featured) VALUES (20, 'Fuente de agua para gato 2 L', 'fuente-de-agua-para-gato-2-l', 'El agua en movimiento invita a tomar más. Filtro de carbón incluido.', 6, 'gato', 'Gatuno', 'Presentación', 0);
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (42, 20, 'Fuente + 1 filtro', 'MAYA-020-1', '2000000000428', 89900, 99900, 3, 2, 0);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (42, 3, 3, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO product_variants (id, product_id, name, sku, barcode, price, compare_at_price, stock, min_stock, sort_order) VALUES (43, 20, 'Repuesto x 3 filtros', 'MAYA-020-2', '2000000000435', 24900, NULL, 10, 3, 1);
INSERT INTO stock_movements (variant_id, delta, stock_after, reason, note, user_name) VALUES (43, 10, 10, 'CREACION', 'Inventario inicial de ejemplo', 'Sistema');
INSERT INTO season_events (slug, name, enabled, starts_at, ends_at, headline, message, cta_label, category_slug, discount_note, featured_product_ids) VALUES ('halloween', 'Halloween', 1, '2026-10-01', '2026-10-31', 'Disfraces, dulces y cero sustos', 'Disfraces cómodos y premios para que tu peludo también pida dulce.', 'Ver premios', 'premios', '', '[6,8,10]');
INSERT INTO season_events (slug, name, enabled, starts_at, ends_at, headline, message, cta_label, category_slug, discount_note, featured_product_ids) VALUES ('navidad', 'Navidad', 0, '2026-12-01', '2026-12-25', 'Navidad con toda la familia', 'Regalos para quien te recibe en la puerta moviendo la cola.', 'Ver regalos', NULL, '', '[]');
INSERT INTO season_events (slug, name, enabled, starts_at, ends_at, headline, message, cta_label, category_slug, discount_note, featured_product_ids) VALUES ('ano-nuevo', 'Año Nuevo', 0, '2026-12-26', '2027-01-06', 'Año nuevo, paseos nuevos', 'Sin pólvora, por favor: todo para una noche tranquila en casa.', 'Ver la colección', NULL, '', '[]');
INSERT INTO season_events (slug, name, enabled, starts_at, ends_at, headline, message, cta_label, category_slug, discount_note, featured_product_ids) VALUES ('amor-amistad', 'Amor y Amistad', 0, '2027-09-01', '2027-09-30', 'Tu mejor amigo tiene cuatro patas', 'Detalles para celebrar a quien te quiere sin condiciones.', 'Ver detalles', NULL, '', '[]');
INSERT INTO staff_users (email, name, roles) VALUES ('luisa@mayapets.co', 'Luisa', '["admin"]');
INSERT INTO staff_users (email, name, roles) VALUES ('ventas@mayapets.co', 'Mostrador', '["vendedor"]');
INSERT INTO staff_users (email, name, roles) VALUES ('adopciones@mayapets.co', 'Equipo de adopciones', '["adopciones"]');
